version: '3.1'

services:
  video-ingest:
    image: kirangershenfeld/youtube-metrics:video-ingest
    container_name: video-ingest
    env_file: "video-ingest/.env"
    network_mode: host
    restart: always  
  job-scheduler:
    image: kirangershenfeld/youtube-metrics:job-scheduler
    container_name: job-scheduler
    env_file: "job-scheduler/.env"
    network_mode: host
    restart: always
