version: '3.1'

services:
  db:
    image: postgres:13.13-alpine3.19
    container_name: postgres
    environment:
      POSTGRES_DB: local-trending
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
    hostname: db