name: Build For Deployment

on:
  push:
    branches:
      - main  
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build local-trending
        uses: docker/build-push-action@v2
        with:
          context: ./services/video-ingest
          dockerfile: ./cmd/server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/local-trending:latest
          build-args: |
            -f cmd/server/Dockerfile
            --platform linux/amd64